version: "3.9"
services:
  web:
    build: .
    ports:
      - "8022:8022"
      - "8023:8023"
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "charon"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "5053"
    ports:
      - "5432:5432"