server:
  port: 8080
spring:
  application:
    name: '@project.name@'
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/charon
    username: postgres
    password: 5053
  jpa:
    show-sql: true
org:
  jobrunr:
    background-job-server:
      enabled: true
    dashboard:
      enabled: false