server:
  port: '@server.port@'
spring:
  application:
    name: '@project.name@'
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/charon
    username: postgres
    password: 5053
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
app:
  integration:
    yookassa: https://api.yookassa.ru/v3
org:
  jobrunr:
    background-job-server:
      enabled: true
    dashboard:
      enabled: false
