server:
  port: '@server.port@'
  servlet:
    context-path: /charon
spring:
  data:
    redis:
      repositories:
        enabled: false
  redis:
    host: 0.0.0.0
    port: 6380
    password: redispw
  quartz:
    job-store-type: jdbc
    properties:
      org:
        quartz:
          threadPool:
            threadCount: 29
            class: org.quartz.simpl.SimpleThreadPool
          jobStore:
            misfireThreshold: 60000
            driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
            isClustered: true
            useProperties: true
    jdbc:
      initialize-schema: never
  application:
    name: '@project.name@'
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/charon
    username: postgres
    password: 5053
    hikari:
      minimum-idle: 5
      maximum-pool-size: 12
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
app:
  stream:
    publisher: REDIS
  redis:
    stream:
      key: payment-stream
      maxlen: 1000
      waitPending: 0
  aws-stream:
    endpoint: 'yds.serverless.yandexcloud.net'
    accessKey: fake-access-key
    secretKey: fake-secret-key
    region: ru-central-1
    uzum-stream:
      name: '/ru-central1/b1gtojcphtuae1n9siie/etnvck8jo3kuh0vilc57/payment'
  scheduler:
    exchange-rate:
      cron: 0 0 1 ? * * *
    evict-currency:
      cron: 0 0 1 ? * * *
    balance-deposit:
      cron: 0 0/1 * * * ?
    purchase-service:
      cron: 0 0/1 * * * ?
  integration:
    posthog:
      api-key: change_me
    currency-api:
      url: https://api.currencyapi.com/v3
      api-key: test-key
    ninja:
      url: https://api.api-ninjas.com/v1
      api-key:
    yookassa:
      url: https://api.yookassa.ru/v3
      secretKey: test-key
      shopId: 817883
    lava:
      url: https://api.lava.ru/business/invoice
      shopId: 45c330f1-a46d-484f-a8e1-524c08df8879
      secretKey: test-key
    enot:
      url: https://api.enot.io/invoice
      shopId: d374961e-f7db-4cf4-a4a9-9caa61e661a8
      secretKey:

freekassa:
  baseUrl: https://api.freekassa.ru
  shopId: 41739
  apiKey: 3359c65680927f67661345031fb0b738
  secretWordFirst: 'mHPoH9jB_BZe%lL'
  secretWordSecond: '{v5T0IKN93p4fKx'

click:
  baseUrl: https://my.click.uz/services/pay
  merchantId: 22733
  serviceId: 30232
  secretKey: someKey
  merchantUserId: 36242



management:
  security:
    flag: false
  server:
    port: '@management.port@'
  metrics:
    prometheus:
      enabled: true
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
